# -*- coding: utf-8 -*-
"""human detecion in .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Uqlc3HiOpylUDxb2qnrzH15SZXWrWNhb
"""

# Commented out IPython magic to ensure Python compatibility.
# Install dependencies
!pip install -q pyheif pillow
!git clone -q https://github.com/ultralytics/yolov5
# %cd yolov5
# %pip install -qr requirements.txt

import pyheif
from PIL import Image
import os
import torch
import glob
import shutil
from google.colab import files
from IPython.display import display

# Load YOLOv5 model
model = torch.hub.load('ultralytics/yolov5', 'yolov5s', pretrained=True)

# Upload image
uploaded = files.upload()
file_path = list(uploaded.keys())[0]

# Convert HEIC to JPG if needed
if file_path.lower().endswith(".heic"):
    jpg_path = file_path.rsplit(".", 1)[0] + ".jpg"

    def convert_heic_to_jpg(heic_path, jpg_path):
        heif_file = pyheif.read(heic_path)
        image = Image.frombytes(
            heif_file.mode,
            heif_file.size,
            heif_file.data,
            "raw",
            heif_file.mode,
            heif_file.stride,
        )
        image.save(jpg_path, "JPEG")

    convert_heic_to_jpg(file_path, jpg_path)
else:
    jpg_path = file_path

# Run detection
results = model(jpg_path)

# Filter detections to only 'person' class (class 0)
person_mask = results.pred[0][:, -1] == 0  # boolean mask for class 0 (person)
person_detections = results.pred[0][person_mask]

import numpy as np

if len(person_detections) > 0:
    # Temporarily replace predictions with persons only
    results.pred[0] = person_detections

    # Render annotated image(s) (returns list of numpy arrays)
    rendered_imgs = results.render()

    # Save the first rendered image (our input image) as jpg
    annotated_img_path = "result_persons.jpg"
    Image.fromarray(rendered_imgs[0]).save(annotated_img_path)

    result_image_path = annotated_img_path
else:
    print("⚠️ No persons detected. Saving original image instead.")
    fallback_path = "result_fallback.jpg"
    shutil.copy(jpg_path, fallback_path)
    result_image_path = fallback_path

# Display result image
display(Image.open(result_image_path))
files.download(result_image_path)

# Print person count
person_count = len(person_detections)
print(f"\nDetected persons: {person_count}")

# Save person count summary to text file and allow download
counts_path = "person_count_summary.txt"
with open(counts_path, "w") as f:
    f.write(f"Detected persons: {person_count}\n")

files.download(counts_path)

print("\n✅ Detection complete and files ready for download.")